### ISSUE TITLE
Update django etc to latest (later) version

### ISSUE THREAD

**Issue by johan-karlsson-goobit-se** [BTCX/BTCX_blockchain#12]
Its currently pinned to run on
djangorestframework 3.1.3
django 1.7.11
bitcoinrpc 0.1

**Comment by sikamedia** [comment]
I will use ANACONDA https://www.continuum.io/ to setup the dev environment at first.

**Comment by sikamedia** [comment]
Mlg,  as python-jsonrpc still supports the old version of python, we have to stay with python 2.7.x. The lastest python 2.7.x should works.  Please upgrade all packages to the latest and test it, I can fix it based on your error report. After all, you have been using for certain years. You know the tricks.

**Comment by johan-karlsson-goobit-se** [comment]
Im actually not even getting that far:

root@test.blockchain.bt.cx:/tmp/BTCX_blockchain/btcxblockchainapi# pip install --upgrade setuptools
Downloading/unpacking setuptools from https://pypi.python.org/packages/b5/e2/cca325e160b8e12334f5b2923ffcdb3c02da9fded1d2899d7930ac1c7448/setuptools-34.3.2.zip#md5=65444b8c4c2aaa6d21305609e3fbe65c
  Downloading setuptools-34.3.2.zip (622Kb): 622Kb downloaded
  Running setup.py egg_info for package setuptools
    Traceback (most recent call last):
      File "<string>", line 3, in <module>
      File "setuptools/__init__.py", line 12, in <module>
        import setuptools.version
      File "setuptools/version.py", line 1, in <module>
        import pkg_resources
      File "pkg_resources/__init__.py", line 70, in <module>
        import packaging.version
    ImportError: No module named packaging.version
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 3, in <module>

  File "setuptools/__init__.py", line 12, in <module>

    import setuptools.version

  File "setuptools/version.py", line 1, in <module>

    import pkg_resources

  File "pkg_resources/__init__.py", line 70, in <module>

    import packaging.version

ImportError: No module named packaging.version

----------------------------------------
Command python setup.py egg_info failed with error code 1 in /tmp/BTCX_blockchain/btcxblockchainapi/build/setuptools


and then if I try to continue anyway:

root@test.blockchain.bt.cx:/tmp/BTCX_blockchain/btcxblockchainapi# pip install --upgrade -r requirements.txt
Downloading/unpacking django from https://pypi.python.org/packages/25/07/b915b82e345c5189ba999dcfdf96d8de7026166c5e16f0e7030ffbe5f6cd/Django-1.11rc1.tar.gz#md5=080665995b322de22a12d0596c081856 (from -r requirements.txt (line 1))
  Downloading Django-1.11rc1.tar.gz (7.8Mb): 7.8Mb downloaded
  Running setup.py egg_info for package django
    /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'entry_points'
      warnings.warn(msg)
    /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'extras_require'
      warnings.warn(msg)
    /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'zip_safe'
      warnings.warn(msg)
    /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'include_package_data'
      warnings.warn(msg)
    /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'install_requires'
      warnings.warn(msg)
    usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: -c --help [cmd1 cmd2 ...]
       or: -c --help-commands
       or: -c cmd --help
    
    error: invalid command 'egg_info'
    Complete output from command python setup.py egg_info:
    /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'entry_points'

  warnings.warn(msg)

/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'extras_require'

  warnings.warn(msg)

/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'zip_safe'

  warnings.warn(msg)

/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'include_package_data'

  warnings.warn(msg)

/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'install_requires'

  warnings.warn(msg)

usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]

   or: -c --help [cmd1 cmd2 ...]

   or: -c --help-commands

   or: -c cmd --help



error: invalid command 'egg_info'

----------------------------------------
Command python setup.py egg_info failed with error code 1 in /tmp/BTCX_blockchain/btcxblockchainapi/build/django

**Comment by sikamedia** [comment]
what is the python version installed for test.blockchain.bt.cx? Try  "python -V" for printing the version number.

**Comment by johan-karlsson-goobit-se** [comment]
root@test.blockchain.bt.cx:/tmp/btcxblockchain/btcxblockchainapi# python -V
Python 2.7.3

root@test.blockchain.bt.cx:/tmp/btcxblockchain/btcxblockchainapi# pip --version
pip 1.1 from /usr/lib/python2.7/dist-packages (python 2.7)

I removed the version of pip installed by apt-get and installed a newer version manually, and now it seems to work!

root@test.blockchain.bt.cx:/tmp/btcxblockchain/btcxblockchainapi# /usr/local/bin/pip --version
pip 9.0.1 from /usr/local/lib/python2.7/dist-packages (python 2.7)

Now Im getting this far:

```
root@test.blockchain.bt.cx:/var/www/btcxblockchainapi# python manage.py runserver 127.0.0.1:8000
Performing system checks...

Unhandled exception in thread started by <function wrapper at 0x2caf5f0>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/runserver.py", line 121, in inner_run
    self.check(display_num_errors=True)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 374, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 361, in _run_checks
    return checks.run_checks(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python2.7/dist-packages/django/core/checks/urls.py", line 24, in check_resolver
    for pattern in resolver.url_patterns:
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python2.7/dist-packages/django/urls/resolvers.py", line 313, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python2.7/dist-packages/django/urls/resolvers.py", line 306, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/var/www/btcxblockchainapi/btcxblockchainapi/urls.py", line 1, in <module>
    from django.conf.urls import patterns, include, url
ImportError: cannot import name patterns
```

**Comment by sikamedia** [comment]
I will fix it by weekend. You can refer to http://stackoverflow.com/questions/8074955/cannot-import-name-patterns, it depicts what should be fixed.

**Comment by sikamedia** [comment]
Pull the latest code and try.

**Comment by johan-karlsson-goobit-se** [comment]
Now it errors with this instead:
```
Unhandled exception in thread started by <function wrapper at 0x30aa668>
Performing system checks...

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/runserver.py", line 121, in inner_run
    self.check(display_num_errors=True)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 420, in check
    raise SystemCheckError(msg)
django.core.management.base.SystemCheckError: SystemCheckError: System check identified some issues:

ERRORS:
?: (urls.E004) Your URL pattern '' is invalid. Ensure that urlpatterns is a list of url() instances.
        HINT: Try removing the string ''. The list of urlpatterns should not have a prefix string as the first element.

System check identified 1 issue (0 silenced).
```

**Comment by sikamedia** [comment]
Solution:  http://stackoverflow.com/questions/38786461/django-error-your-url-pattern-is-invalid-ensure-that-urlpatterns-is-a-list-of

I will fix this, will inform when it is ready.

**Comment by sikamedia** [comment]
Pull the latest code and try. The problem should be fixed.

**Comment by johan-karlsson-goobit-se** [comment]
Is a bit better!

Im using this commit:
https://github.com/BTCX/BTCX_blockchain/commit/a45984eeb6c4449bf5200829b1e7857926e3ac3b

And starting the app by doing
```python manage.py runserver 127.0.0.1:8000```

This is the output:

```root@test.blockchain.bt.cx:/var/www/btcxblockchainapi# python manage.py runserver 127.0.0.1:8000 &
[2] 6481
root@test.blockchain.bt.cx:/var/www/btcxblockchainapi# Performing system checks...

Unhandled exception in thread started by <function wrapper at 0x33e25f0>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/runserver.py", line 121, in inner_run
    self.check(display_num_errors=True)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 420, in check
    raise SystemCheckError(msg)
django.core.management.base.SystemCheckError: SystemCheckError: System check identified some issues:

ERRORS:
?: (urls.E004) Your URL pattern '' is invalid. Ensure that urlpatterns is a list of url() instances.
	HINT: Try removing the string ''. The list of urlpatterns should not have a prefix string as the first element.

System check identified 1 issue (0 silenced).
^M
root@test.blockchain.bt.cx:/var/www/btcxblockchainapi# 
root@test.blockchain.bt.cx:/var/www/btcxblockchainapi# 
root@test.blockchain.bt.cx:/var/www/btcxblockchainapi# 
root@test.blockchain.bt.cx:/var/www/btcxblockchainapi# 
root@test.blockchain.bt.cx:/var/www/btcxblockchainapi# netstat -tupln
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      31617/sshd      
tcp        0      0 127.0.0.1:25            0.0.0.0:*               LISTEN      1457/exim4      
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN      27869/nginx     
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      27869/nginx     
root@test.blockchain.bt.cx:/var/www/btcxblockchainapi# ```

It does start, but there is no server at port 8080. Do you know why that is?

**Comment by johan-karlsson-goobit-se** [comment]
More info!

I tried with an older version of Django:

```pip install --force-reinstall --upgrade Django==1.7.11```

And then the web server did start, but with an error:

```
Environment:


Request Method: GET
Request URL: http://localhost:8000/

Django Version: 1.7.11
Python Version: 2.7.3
Installed Applications:
('django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'rest_framework',
 'btcrpc')
Installed Middleware:
('django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware')


Traceback:
File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py" in get_response
  98.                 resolver_match = resolver.resolve(request.path_info)
File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py" in resolve
  343.             for pattern in self.url_patterns:
File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py" in url_patterns
  372.         patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py" in urlconf_module
  366.             self._urlconf_module = import_module(self.urlconf_name)
File "/usr/lib/python2.7/importlib/__init__.py" in import_module
  37.     __import__(name)
File "/var/www/btcxblockchainapi/btcxblockchainapi/urls.py" in <module>
  2. from rest_framework import routers
File "/usr/local/lib/python2.7/dist-packages/rest_framework/routers.py" in <module>
  25. from rest_framework import views
File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py" in <module>
  20. from rest_framework.response import Response
File "/usr/local/lib/python2.7/dist-packages/rest_framework/response.py" in <module>
  13. from rest_framework.serializers import Serializer
File "/usr/local/lib/python2.7/dist-packages/rest_framework/serializers.py" in <module>
  23. from django.db.models import DurationField as ModelDurationField

Exception Type: ImportError at /
Exception Value: cannot import name DurationField
```

I then also downgraded djangorestframework

```pip install --force-reinstall --upgrade djangorestframework==3.1.3```

Now it starts.... but we're still on old versions.

**Comment by sikamedia** [comment]
Lets hold a while, I will give you an instruction how to test it later when it is done properly.

**Comment by ViktorTigerstrom** [comment]
Pushed fixes in branch Django_upate that supports Django 1.11.10 and djangorestframework 3.7.7
