### ISSUE TITLE
bitcoins transfer script error. 

### ISSUE THREAD

**Issue by sikamedia** [BTCX/BTCX_blockchain#8]
blockchain@test:/var/www/btcxblockchainapi$ python run_transfer.py 
Traceback (most recent call last):
  File "run_transfer.py", line 120, in <module>
    run_transfer.main()
  File "run_transfer.py", line 65, in main
    total_amount = self.__get_total_amount_in_wallet()
  File "run_transfer.py", line 34, in __get_total_amount_in_wallet
    return reduce(lambda (coin_value), y: coin_value + y, self.coin_to_be_send_dict.values())
TypeError: reduce() of empty sequence with no initial value

**Comment by johan-karlsson-goobit-se** [comment]
This can be closed?
